Disable "Block Network Communication" and "ASCS Node Crash" test cases in input-api.yaml; update ERS node IP retrieval method in block-network.yml

diff --git a/src/roles/ha_scs/tasks/block-network.yml b/src/roles/ha_scs/tasks/block-network.yml
--- a/src/roles/ha_scs/tasks/block-network.yml
+++ b/src/roles/ha_scs/tasks/block-network.yml
@@ -35,21 +35,43 @@
 
         - name:                         "Test Execution: Get peer ERS node IP address"
           ansible.builtin.set_fact:
-            ers_ip:                     "{{ hostvars[cluster_status_pre.ers_node].ansible_default_ipv4.address }}"
+            ers_ip:                     "{{ hostvars[cluster_status_pre.ers_node].ansible_host }}"
           register:                     ers_ip_result
 
         - name:                         "Test Execution: Block network communication"
           ansible.builtin.shell: |
-                                        iptables -I INPUT -s {{ ers_ip }} -j DROP;
-                                        iptables -I OUTPUT -d {{ ers_ip }} -j DROP
+                                        iptables -A INPUT -s {{ ers_ip }} -j DROP;
+                                        iptables -A OUTPUT -d {{ ers_ip }} -j DROP
           register:                     block_network_result
 
         - name:                         "Test Execution: Wait for failover"
           ansible.builtin.pause:
             seconds:                    60
 
+    - name:                             "Test Execution: Check node status on primary and secondary"
+      block:
+        - name:                         "Test Execution: Check node connectivity from controller"
+          delegate_to:                  localhost
+          ansible.builtin.shell: |
+                                        for i in $(seq 1 30); do
+                                          if ! ping -c 1 -w 1 {{ ansible_host }}; then
+                                            echo "Connection failed on attempt $i"
+                                            exit 1
+                                          fi
+                                          sleep 1
+                                        done
+          register:                     node_status
+          ignore_errors:                true
+
+        - name:                         "Set Node Status Facts"
+          ansible.builtin.set_fact:
+            ascs_node_down:          "{{ hostvars[cluster_status_pre.ascs_node].node_status is failed }}"
+            ers_node_down:        "{{ hostvars[cluster_status_pre.ers_node].node_status is failed }}"
+
     - name:                             "Test Execution: Monitor failover on ERS Node"
-      when:                             ansible_hostname == cluster_status_pre.ers_node
+      when:
+                                        - ansible_hostname == cluster_status_pre.ers_node
+                                        - ascs_node_down and not ers_node_down
       become:                           true
       block:
         - name:                         "Test Execution: Validate SCS cluster status"
@@ -65,9 +87,23 @@
                                         and cluster_status_test_execution.ers_node == cluster_status_pre.ascs_node
 
     - name:                             "Test Execution: Restore Network on ASCS Node"
-      when:                             ansible_hostname == cluster_status_pre.ascs_node
+      when:
+                                        - ansible_hostname == cluster_status_pre.ascs_node
+                                        - not ascs_node_down and ers_node_down
       become:                           true
       block:
+        - name:                         "Test Execution: Validate SCS cluster status"
+          get_cluster_status_scs:
+            sap_sid:                    "{{ sap_sid | lower }}"
+            ansible_os_family:          "{{ ansible_os_family | upper }}"
+          register:                     cluster_status_test_execution
+          retries:                      50
+          delay:                        10
+          failed_when:                  false
+          until: |
+                                        cluster_status_test_execution.ascs_node == cluster_status_pre.ers_node
+                                        and cluster_status_test_execution.ers_node == cluster_status_pre.ascs_node
+
         - name:                         "Test Execution: Restore network communication"
           ansible.builtin.shell: |
                                         iptables -D INPUT -s {{ ers_ip }} -j DROP;
